# Generated by Django 3.2.2 on 2022-05-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='mark',
            field=models.CharField(blank=True, choices=[['Right', 'Right'], ['Wrong', 'Wrong']], max_length=30, null=True),
        ),
    ]
