# Generated by Django 4.0.4 on 2022-05-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_answer_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='keyword',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_question',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
